gratacels/gratacels/urls.py
from django.conf.urls import patterns, include, url

from igratacels.views import *

from django.utils import timezone
from django.views.generic import DetailView, ListView, UpdateView
from igratacels.models import *
from igratacels.forms import EstilForm, MaterialForm, ArquitecteForm, GratacelForm
from igratacels.views import MaterialCreate, EstilCreate, ArquitecteCreate, GratacelCreate
from igratacels.views import APIGratacelList, APIGratacelDetail, APIEstilList, APIEstilDetail, \
			     APIMaterialList, APIMaterialDetail, APIArquitecteList, APIArquitecteDetail

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()



urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gratacels.views.home', name='home'),
    # url(r'^gratacels/', include('gratacels.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

#OTHER URL
    url(r'^admin/', include(admin.site.urls)), 
    url(r'^$', mainpage, name='home'),
    url(r'^home', mainpage, name='home'),
    url(r'^user/(\w+)/$', userpage),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout'),

#CREATE URL
    url(r'^materials/create/$',
	MaterialCreate.as_view(),
	name='material_create'),
    url(r'^estils/create/$',
	EstilCreate.as_view(),
	name='estil_create'),
    url(r'^arquitectes/create/$',
	ArquitecteCreate.as_view(),
	name='arquitecte_create'),
    url(r'^gratacels/create/$',
	GratacelCreate.as_view(),
	name='gratacel_create'),

#EDIT URL
    url(r'^material/(?P<pk>\d+)/edit/$',
	 UpdateView.as_view(model = Material, 
	 template_name = 'form.html',
	 form_class = MaterialForm),
	 name='material_edit'),
    url(r'^estil/(?P<pk>\d+)/edit/$',
	 UpdateView.as_view(model = Estil, 
	 template_name = 'form.html',
	 form_class = EstilForm),
	 name='estil_edit'),
    url(r'^arquitecte/(?P<pk>\d+)/edit/$',
	 UpdateView.as_view(model = Arquitecte, 
	 template_name = 'form.html',
	 form_class = ArquitecteForm),
	 name='arquitecte_edit'),
    url(r'^gratacel/(?P<pk>\d+)/edit/$',
	 UpdateView.as_view(model = Gratacel, 
	 template_name = 'form.html',
	 form_class = GratacelForm), 
	 name='gratacel_edit'),

#LIST URL
    url(r'^gratacels/', gratacel_list,
	name='gratacel_list'),
    url(r'^arquitectes/$', 'igratacels.views.arquitecte_list',
	name='arquitecte_list'),
    url(r'^estils/$', 'igratacels.views.estil_list',
	name='estil_list'),
    url(r'^materials/$', 'igratacels.views.material_list',
	name='material_list'),

#DETAIL URL	
    url(r'^gratacel/(?P<idGratacel>\d+)$',
	'igratacels.views.gratacelpage',
	name='gratacel_detail'),
    url(r'^arquitecte/(?P<idArquitecte>\d+)$',
	'igratacels.views.arquitectepage',
	name='arquitecte_detail'),
    url(r'^estil/(?P<idEstil>\d+)$',
	'igratacels.views.estilpage',
	name='estil_detail'),
    url(r'^material/(?P<idMaterial>\d+)/$',
	'igratacels.views.materialpage',
	name='material_detail'),

    # Url per afegir reviews
    url(r'^gratacel/(?P<idGratacel>\d+)/reviews/create$',
	'igratacels.views.review',
	name='review_create'),
    



#DELETE URL	
    url(r'^gratacel/(?P<pk>\d+)/delete/$',
	GratacelDelete.as_view(),
	name='gratacel_delete'),
    url(r'^arquitecte/(?P<pk>\d+)/delete/$',
	ArquitecteDelete.as_view(),
	name='arquitecte_delete'),
    url(r'^estil/(?P<pk>\d+)/delete/$',
	EstilDelete.as_view(),
	name='estil_delete'),
    url(r'^material/(?P<pk>\d+)/delete/$',
	MaterialDelete.as_view(),
	name='material_delete'),




#API URL
url(r'^api/gratacels/$', APIGratacelList.as_view(), name='gratacel-list'),
url(r'^api/gratacel/(?P<pk>\d+)/$', APIGratacelDetail.as_view(), name='gratacel-detail'),
url(r'^api/materials/$', APIMaterialList.as_view(), name='material-list'),
url(r'^api/material/(?P<pk>\d+)/$', APIMaterialDetail.as_view(), name='material-detail'),
url(r'^api/estils/$', APIEstilList.as_view(), name='estil-list'),
url(r'^api/estil/(?P<pk>\d+)/$', APIEstilDetail.as_view(), name='estil-detail'),
url(r'^api/arquitectes/$', APIArquitecteList.as_view(), name='arquitecte-list'),
url(r'^api/arquitecte/(?P<pk>\d+)/$', APIArquitecteDetail.as_view(), name='arquitecte-detail'),

)

gratacels/igratacels/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from datetime import date

# Create your models here.

class Arquitecte (models.Model):
	idArquitecte = models.AutoField(primary_key=True)
	nom = models.TextField(max_length=25)
	cognom = models.TextField(max_length=25)
	data_naixement = models.DateField()
	data_defuncio = models.DateField(blank=True,null=True)
	nacionalitat = models.TextField(max_length=25)
	imatge = models.TextField()
	user = models.ForeignKey(User)
	date = models.DateField(default=date.today)

	def __unicode__(self):
		return u"%s, %s" % (self.cognom, self.nom)
	def get_absolute_url(self):
		return reverse('arquitecte_detail', kwargs={'idArquitecte': self.pk})

class Material (models.Model):
	idMaterial = models.AutoField(primary_key=True)
	nom = models.TextField(max_length=25)
	densitat = models.FloatField()
	cost = models.FloatField()
	user = models.ForeignKey(User)
	date = models.DateField(default=date.today)

	def __unicode__(self):
		return u"%s" % self.nom
	def get_absolute_url(self):
		return reverse('material_detail', kwargs={'idMaterial': self.pk})

class Estil (models.Model): 
	idEstil = models.AutoField(primary_key=True)
	nom = models.TextField(max_length=25)
	dataInici = models.IntegerField(max_length=4)
	dataFi = models.IntegerField(max_length=4, blank = True,null=True)
	user = models.ForeignKey(User)
	date = models.DateField(default=date.today)

	def __unicode__(self):
		return u"%s" % self.nom
	def get_absolute_url(self):
		return reverse('estil_detail', kwargs={'idEstil': self.pk})

class Gratacel (models.Model):
	idGratacel = models.AutoField(primary_key=True)
	nom = models.TextField(max_length=25)
	altura = models.IntegerField()
	altura_terrat = models.IntegerField()
	num_plantes = models.IntegerField()
	ciutat = models.TextField(max_length=25)
	pais = models.TextField(max_length=25)
	any_inici = models.IntegerField()
	idEstil = models.ForeignKey(Estil)
	posicio_ranking = models.IntegerField(blank=True, null=True)
	arquitectes = models.ManyToManyField(Arquitecte)
	materials = models.ManyToManyField(Material)
	imatge = models.TextField()
	user = models.ForeignKey(User)
	date = models.DateField(default=date.today)
	
	def __unicode__(self):
		return u"%s" % self.nom
	def get_absolute_url(self):
		return reverse('gratacel_detail', kwargs={'idGratacel': self.pk})
	def averageRating(self):
		countTotal = 0.0
		countNum = 0
		for review in self.gratacelreview_set.all():
			countNum +=1
			countTotal += review.rating
		return countTotal/countNum

class Review(models.Model):
    RATING_CHOICES = ((1, '1'), (2, '2'), (3,'3'), (4,'4'), (5, '5'))	 	
    rating  =  models.PositiveSmallIntegerField('Ratings (stars)', blank=False, default=3, choices=RATING_CHOICES)	
    comment = models.TextField(blank=True,  null=True)	
    user  =  models.ForeignKey(User)	
    date = models.DateField(default=date.today)	
    #class Meta:	
	#abstract  =  True	
  
class GratacelReview(Review):
    gratacel = models.ForeignKey(Gratacel)

gratacels/igratacels/forms.py
from django.forms import ModelForm
from models import *

class EstilForm(ModelForm):
	class Meta:
		model = Estil
		exclude = ('user', 'date', 'idEstil')

class MaterialForm(ModelForm):
	class Meta:
		model = Material
		exclude = ('user', 'date', 'idMaterial')

class ArquitecteForm(ModelForm):
	class Meta:
		model = Arquitecte
		exclude = ('user', 'date', 'idArquitecte')

class GratacelForm(ModelForm):
	class Meta:
		model = Gratacel
		exclude = ('user', 'date', 'idGratacel')

gratacels/igratacels/views.py
# Create your views here.

from django.http import HttpResponse, Http404
from django.contrib.auth.models import User
from django.template import Context,RequestContext
from django.template.loader import get_template
from django.shortcuts import render_to_response
from igratacels.models import *
from forms import *
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.core.urlresolvers import reverse_lazy
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from rest_framework import generics, permissions
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from serializers import ArquitecteSerializer, EstilSerializer, MaterialSerializer, GratacelSerializer



def mainpage(request):
	return render_to_response(
		'mainpage.html',
		{
			'titlehead': 'Gratacels aPP',
			'pagetitle': 'Welcome to the Gratacels aPPlication',
			'contentbody': 'Managing non legal funding since 2013',
			'user': request.user

		})
	output = template.render(variables)
	return HttpResponse(output)

def gratacelpage(request, idGratacel):

	try:
		gratacel = Gratacel.objects.get(idGratacel=idGratacel)
	except:
		raise Http404('Gratacel no trobat')

	parametre = request.GET.get('format','')
	if parametre =="XML":
		template = get_template('gratacelpage.xml')
	elif parametre =="JSON":
		template = get_template('gratacelpage.js')	
	else:
		template = get_template('gratacelpage.html')
	arquitectes = gratacel.arquitectes.all()
	materials = gratacel.materials.all()
	estils = Estil.objects.get(idEstil=gratacel.idEstil_id)
	reviews = GratacelReview.objects.all().filter(gratacel=idGratacel)
	RATING_CHOICES = GratacelReview.RATING_CHOICES
	#reviews = gratacel.gratacelreview_set.all()
	variables = Context({
		'gratacel': gratacel,
		'arquitectes': arquitectes,
		'estils': estils,
		'materials': materials,
		'reviews': reviews,
		'user': request.user,
		'RATING_CHOICES': RATING_CHOICES
		})
	#output = template.render(variables)
	return render_to_response('gratacelpage.html', variables, context_instance=RequestContext(request))

def gratacel_list(request):
	try:
		gratacels = Gratacel.objects.all()
	except:
		raise Http404('Materials no trobats')

	parametre = request.GET.get('format','')
	if parametre =="XML":
		template = get_template('gratacel_list.xml')
	elif parametre =="JSON":
		template = get_template('gratacel_list.js')	
	else:
		template = get_template('gratacel_list.html')

	variables = Context({
		'titlehead': 'Gratacels aPP',
		'pagetitle': 'Welcome to the Gratacels aPPlication',
		'contentbody': 'Managing non legal funding since 2013',
		'gratacels': gratacels,
		'user': request.user
		})
	output = template.render(variables)
	return HttpResponse(output)

def arquitectepage(request, idArquitecte):

	try:
		arquitecte = Arquitecte.objects.get(idArquitecte=idArquitecte)
	except:
		raise Http404('Arquitecte no trobat')

	parametre = request.GET.get('format','')
	if parametre =="XML":
		template = get_template('arquitectepage.xml')
	elif parametre =="JSON":
		template = get_template('arquitectepage.js')	
	else:
		template = get_template('arquitectepage.html')

	gratacels=arquitecte.gratacel_set.all()
	variables = Context({
		'arquitecte': arquitecte,
		'gratacels': gratacels,
		'user': request.user
		})
	output = template.render(variables)
	return HttpResponse(output)

def estilpage(request, idEstil):

	try:
		estil = Estil.objects.get(idEstil=idEstil)
	except:
		raise Http404('Estil no trobat')
	parametre = request.GET.get('format','')
	if parametre =="XML":
		template = get_template('estilpage.xml')
	elif parametre =="JSON":
		template = get_template('estilpage.js')	
	else:
		template = get_template('estilpage.html')

	gratacels=estil.gratacel_set.all()	
	variables = Context({
		'estil': estil,
		'gratacels': gratacels,
		'user': request.user
		})
	output = template.render(variables)
	return HttpResponse(output)

def materialpage(request, idMaterial):

	try:
		material = Material.objects.get(idMaterial=idMaterial)
	except:
		raise Http404('Material no trobat')
	
	parametre = request.GET.get('format','')
	if parametre =="XML":
		template = get_template('materialpage.xml')
	elif parametre =="JSON":
		template = get_template('materialpage.js')	
	else:
		template = get_template('materialpage.html')
	gratacels=material.gratacel_set.all()
	
	variables = Context({
		'material': material,
		'gratacels': gratacels,
		'user': request.user
		})
	output = template.render(variables)
	return HttpResponse(output)

def arquitecte_list(request):
	try:
		arquitectes = Arquitecte.objects.all()
	except:
		raise Http404('Arquitectes no trobats')

	parametre = request.GET.get('format','')
	if parametre =="XML":
		template = get_template('arquitecte_list.xml')
	elif parametre =="JSON":
		template = get_template('arquitecte_list.js')	
	else:
		template = get_template('arquitecte_list.html')
	
	
	variables = Context({
		'titlehead': 'Gratacels aPP',
		'pagetitle': 'Welcome to the Gratacels aPPlication',
		'contentbody': 'Managing non legal funding since 2013',
		'arquitectes': arquitectes,
		'user': request.user
		})
	output = template.render(variables)
	return HttpResponse(output)

def material_list(request):
	try:
		materials = Material.objects.all()
	except:
		raise Http404('Materials no trobats')

	parametre = request.GET.get('format','')
	if parametre =="XML":
		template = get_template('material_list.xml')
	elif parametre =="JSON":
		template = get_template('material_list.js')	
	else:
		template = get_template('material_list.html')

	
	variables = Context({
		'titlehead': 'Gratacels aPP',
		'pagetitle': 'Welcome to the Gratacels aPPlication',
		'contentbody': 'Managing non legal funding since 2013',
		'materials': materials,
		'user': request.user
		})
	output = template.render(variables)
	return HttpResponse(output)

def estil_list(request):
	try:
		estils = Estil.objects.all()
	except:
		raise Http404('Materials no trobats')

	parametre = request.GET.get('format','')
	if parametre =="XML":
		template = get_template('estil_list.xml')
	elif parametre =="JSON":
		template = get_template('estil_list.js')	
	else:
		template = get_template('estil_list.html')

	
	variables = Context({
		'titlehead': 'Gratacels aPP',
		'pagetitle': 'Welcome to the Gratacels aPPlication',
		'contentbody': 'Managing non legal funding since 2013',
		'estils': estils,
		'user': request.user
		})
	output = template.render(variables)
	return HttpResponse(output)

def userpage(request, username):

	try:
		user = User.objects.get(username=username)
	except:
		raise Http404('User not found.')
	
	template = get_template('userpage.html')
	variables = Context({
		'username': username,
		})
	output = template.render(variables)
	return HttpResponse(output)

def review(request, idGratacel):
    gratacel = get_object_or_404(Gratacel, idGratacel=idGratacel)
#    review = Review(
#        rating=request.POST['rating'],
#        comment=request.POST['comment'],
#        user=request.user)
#    review.save()    
#    reviewGratacel = GratacelReview(
#	review = review
#	gratacel = gratacel)

    review = GratacelReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        gratacel=gratacel)
    review.save()
    return HttpResponseRedirect(reverse('gratacel_detail', args=(gratacel.idGratacel,)))

class GratacelDetail (DetailView):
	model = Gratacel
	template_name = 'gratacelpage.html'

	def get_context_data(self, **kwargs):
		context = super(GratacelDetail, self).get_context_data(**kwargs)
		return context

class EstilDetail (DetailView):
	model = Estil
	template_name = 'estilpage.html'

	def get_context_data(self, **kwargs):
		context = super(EstilDetail, self).get_context_data(**kwargs)
		return context

class MaterialDetail (DetailView):
	model = Material
	template_name = 'materialpage.html'

	def get_context_data(self, **kwargs):
		context = super(MaterialDetail, self).get_context_data(**kwargs)
		return context

class ArquitecteDetail (DetailView):
	model = Arquitecte
	template_name = 'arquitectepage.html'

	def get_context_data(self, **kwargs):
		context = super(ArquitecteDetail, self).get_context_data(**kwargs)
		return context

#CREATES
	
class EstilCreate (CreateView):
	model = Estil
	template_name = 'form.html'
	form_class = EstilForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(EstilCreate, self).form_valid(form)

class MaterialCreate (CreateView):
	model = Material
	template_name = 'form.html'
	form_class = MaterialForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(MaterialCreate, self).form_valid(form)

class ArquitecteCreate (CreateView):
	model = Arquitecte
	template_name = 'form.html'
	form_class = ArquitecteForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(ArquitecteCreate, self).form_valid(form)

class GratacelCreate (CreateView):
	model = Gratacel
	template_name = 'form.html'
	form_class = GratacelForm

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super(GratacelCreate, self).form_valid(form)

#DELETES

class MaterialDelete(DeleteView):
	model = Material
	template_name = 'delete.html'
	success_url = reverse_lazy('material_list')

class EstilDelete(DeleteView):
	model = Estil
	template_name = 'delete.html'
	success_url = reverse_lazy('estil_list')

class ArquitecteDelete(DeleteView):
	model = Arquitecte
	template_name = 'delete.html'
	success_url = reverse_lazy('arquitecte_list')

class GratacelDelete(DeleteView):
	model = Gratacel
	template_name = 'delete.html'
	success_url = reverse_lazy('gratacel_list')

#API RESTFUL
class APIGratacelList(generics.ListCreateAPIView):
	model = Gratacel

gratacels/igratacels/templates/arquitectepage.html
{% extends "base.html"%}

{% block head %}
	<meta name="keywords" content="gratacels, estils, arquitectes, materials" />
	<meta name="description" content="Dades de l'arquitecte" />
	<meta name="robots" content="all" />
	<title>Gratacels DataBase: {{arquitecte.cognom}}, {{arquitecte.nom}}</title>
{% endblock %}
{% block content %}
<span vocab="http://schema.org/"  typeof="Person">	
<img property="image" src="/static/img/{{arquitecte.imatge}}" id="fotoarquitecte" alt="fotografia del arquitecte {{arquitecte.nom}}"/>

<h1>Dades del Arquitecte {{arquitecte.cognom}}, {{arquitecte.nom}}
	{% if user = arquitecte.user %}
		<button onclick="window.location.href='/arquitecte/{{arquitecte.idArquitecte}}/edit/'">
			<img src="/static/img/edit.png" alt="button edit"/>
		</button>
	{% endif %}
</h1>

<ul>
<li>Nom: <span property="name">{{arquitecte.nom}}</span></li>
<li>Cognom: <span property="familyName">{{arquitecte.cognom}}</span></li>
<li>Data Naixement: <sapn property="birthDate">{{arquitecte.data_naixement}}</span></li>
<li>Data Defuncio: <sapn property="deathDate">{{arquitecte.data_defuncio}}</span></li>
<li>Nacionalitat: <span property="nationality">{{arquitecte.nacionalitat}}</span></li>
</ul>
</span>

<h2>Gratacels construits:</h2>
{% if gratacels %}
<ol>
{% for gratacel in gratacels %}
<li>
<a href="/gratacel/{{gratacel.idGratacel}}">{{gratacel.nom}}</a> - {{ gratacel.ciutat}} - {{ gratacel.altura }}m
</li>
{% endfor %}
</ol>
{% else %}
<p>No ha construit gratacels.</p>
{% endif %}
{% endblock %}

gratacels/igratacels/templates/base.html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ca" >
<head>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  

	
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="David Hernández, David Canudes, Saida Javierre" />
	{% block head %}	
	<meta name="keywords" content="gratacels, estils, arquitectes, materials" />
	<meta name="description" content="Llista d'arquitectes" />
	<meta name="robots" content="all" />
	<title>Gratacels DataBase: Llista d'arquitectes</title>
	{% endblock %}

	<style type="text/css" title="./currentStyle" media="all">
		@import "/static/global.css";
	</style>
</head>

<body>
<div id="wrapper">
  <div id="head">
    <img class="header_image" src="/static/img/header_image.jpg" alt="Header image"></img>
    <img class="icon" src="/static/img/logo.jpg" alt="Logo"></img>
    <h1>Gratacels</h1>
    <h2>DataBase</h2>
  </div>
  <div id="main">
    <div id="navi">
	{% if user.username %}
		<h2> Benvingut {{ user.username }} </h2>
		<a href="/logout">Sortir</a>
	{% else %}<a href="/login">Login</a>
	{% endif %}	
	<ul>
	  <li><a href="/">Home</a></li>
	  <li><a href="/gratacels">Gratacels</a></li>
	  <li><a href="/arquitectes">Arquitectes</a></li>
	  <li><a href="/estils">Estils</a></li>
	  <li><a href="/materials">Materials</a></li>
	</ul>
	
   </div>
   <div class="ic"></div>
   <div id="content">
   {% block content%}
	 {% if error_message%} <p><strong>{{error_message}}</strong></p>{% endif %}
   {% endblock %}
   </div>
   <div id="footer"><p> Autors: David Hernández, David Canudes, Saida Javierre </p></div>
</div>

</body>
</html>

gratacels/igratacels/templates/delete.html
{% extends "base.html" %}
{% block content %}
<h1>Estas Segur que vols esborrar el objecte???</h1>
	<form method="post" action="">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<input type="submit" value="Si"/>
	</form>
		<input type="button" onclick="history.back()" value="No"/>
{% endblock %}

gratacels/igratacels/templates/estil_list.html
{% extends "base.html"%}

{% block head %}
	<meta name="keywords" content="gratacels, estils, arquitectes, materials" />
	<meta name="description" content="Llista d'estils arquitectònics" />
	<meta name="robots" content="all" />
	<title>Gratacels DataBase: Llista d'estils arquitectònics</title>
{% endblock %}
{% block content %}


<h1>Estils
	{% if user.username %}
		<button onclick="window.location.href='/estils/create/'"><img src="/static/img/add.png" alt="button add"/></button>
	{% endif %}
</h1>
{% if estils %}
<table>
<thead>
<tr><td>Nom</td><td>Any Inici</td><td>Any Final</td><td></td></tr>
</thead>
{% for estil in estils %}
<tr>
<td><a href="/estil/{{estil.idEstil}}"> {{estil.nom}}</a></td><td> {{estil.dataInici}}</td><td>{{estil.dataFi}}</td><td>
	{% if user = estil.user %}
		<button onclick="window.location.href='/estil/{{estil.idEstil}}/edit/'">
			<img src="/static/img/edit.png" alt="button edit"/>
		</button>
		<button onclick="window.location.href='/estil/{{estil.idEstil}}/delete/'">
			<img src="/static/img/delete.png" alt="button delete"/>
		</button>
	{% endif %}</td>
</tr>
{% endfor %}
</table>
{% else %}
<p>No hi ha estils a la base de dades</p>
{% endif %}
{% endblock %}

gratacels/igratacels/templates/estilpage.html
{% extends "base.html"%}

{% block head %}
	<meta name="keywords" content="gratacels, estils, arquitectes, materials" />
	<meta name="description" content="Dades de l'estil arquitectònic" />
	<meta name="robots" content="all" />
	<title>Gratacels DataBase: {{estil.nom}}</title>
{% endblock %}
{% block content %}
	
<h1>Dades del Estil {{estil.nom}}
	{% if user = estil.user %}
		<button onclick="window.location.href='/estil/{{estil.idEstil}}/edit/'">
			<img src="/static/img/edit.png" alt="button edit"/>
		</button>
	{% endif %}
</h1>
<ul>
<li>Any Inici: {{estil.dataInici}}</li>
<li>Any Fi: {{estil.dataFi}}</li>
</ul>

<h2>Gratacels construits amb el estil:</h2>
{% if gratacels %}
<ol>
{% for gratacel in gratacels %}
<li>
<a href="/gratacel/{{gratacel.idGratacel}}">{{gratacel.nom}}</a> - {{ gratacel.ciutat}} - {{ gratacel.altura }}m
</li>
{% endfor %}
</ol>
{% else %}
<p>No hi ha construit gratacels en aquest estil.</p>
{% endif %}
{% endblock %}

gratacels/igratacels/templates/form.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}

<script>
   $(function() {
            $.getJSON("{% static "countries.json" %}", {}, function (countries) {
                $("#id_nacionalitat").autocomplete({
                    source: countries
                });
            });

	   $("#id_ciutat").autocomplete({
                source: function( request, response ) {
                    $.ajax({
                        url: "http://ws.geonames.org/searchJSON",
                        dataType: "jsonp",
                        data: {
                            featureClass: "P",
                            maxRows: 10,
                            name_startsWith: request.term
                        },
                        success: function( data ) {
                            response( $.map( data.geonames, function( item ) {
                                return {
                                    label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
                                    value: item.name,
				    countryName: item.countryName
                                }
                            }));
                        }
                    });
                },
                minLength: 2,
		select: function( event, ui ) {
			if (ui.item) {
				$("#id_pais").val(ui.item.countryName);
			}
			}
	        });
   });
</script>




 


<form method="post" enctype="multipart/form-data" action="">
{% csrf_token %}
<table>
{{ form.as_table }}
</table>
<input type="submit" value="Enviar"/>
</form>
{% endblock %}

gratacels/igratacels/templates/material_confirm_delete.html
{% extends "base.html" %}
{% block content %}

{% endblock %}